name: humcd-upstream
channels:
  - conda-forge
dependencies:
  - python=3.9.23
  - pip=25.2
  - numpy=1.26.4
  - scipy=1.13.1
  - scikit-learn=1.5.2
  - scikit-image=0.19.3
  - matplotlib=3.8.4
  - tqdm=4.67.1
  - pillow=10.4.0
  - pandas=2.2.3
  - joblib=1.4.2
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - torch==2.2.2+cpu
      - torchvision==0.17.2+cpu
      - timm==0.6.13
      - scikit-dimension==0.3.4
      - opencv-python-headless==4.10.0.84
      - segment_anything @ git+https://github.com/facebookresearch/segment-anything.git@dca509fe793f601edb92606367a655c15ac00fdf
