#!/usr/bin/env python3
"""Render a private, offline documentary review bundle from verified evidence.
No predictions or clinical image classifications; preserves editable review CSV.
"""
import csv,hashlib,html,json,shutil
from pathlib import Path
from datetime import datetime,timezone
ROOT=Path(__file__).resolve().parents[1];D=ROOT/'artifacts/bunya/next-phase-20260921/derm7pt-review';B=D/'bundle'
def read(n):return json.loads((D/n).read_text())
def csvrows(n):return list(csv.DictReader((D/n).open(encoding='utf-8-sig')))
def e(s):return html.escape(str(s))
def tab(headers,rows):return '<div class="scroll"><table><thead><tr>'+''.join('<th>'+e(x)+'</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(v)+'</td>' for v in row)+'</tr>' for row in rows)+'</tbody></table></div>'
CSS='''*{box-sizing:border-box}body{margin:0;background:#f3f5f8;color:#182433;font:16px/1.6 system-ui,sans-serif}main{max-width:1380px;margin:auto;padding:28px}h1{font-size:34px;line-height:1.25}h2{margin-top:36px;font-size:25px}h3{font-size:21px}a{color:#185e9c}p{max-width:1120px}.en{color:#435264}.banner,.card{background:white;padding:24px;margin:24px 0;border:1px solid #d6dfe8;border-radius:10px}.banner{border-left:5px solid #407696}.tag{background:#e9f1f8;padding:4px 10px;border-radius:4px;font-size:14px}.pair{display:grid;grid-template-columns:1fr 1fr;gap:24px}.pair figure{margin:0}.pair img{display:block;width:100%;height:auto;background:#eee}.pair figcaption{font-weight:600;padding:8px 0}.scroll{overflow-x:auto}table{border-collapse:collapse;width:100%;font-size:14px}th,td{padding:10px;border-bottom:1px solid #dbe2e9;text-align:left;vertical-align:top}th{background:#eaf0f6}code,pre{overflow-wrap:anywhere;white-space:pre-wrap;font-size:13px}pre{background:#f5f7fa;padding:14px}details{margin:14px 0}summary{cursor:pointer;font-weight:600}.fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}label{display:block;font-size:14px}input,select,textarea{font:inherit;width:100%;padding:8px;border:1px solid #adb9c8;background:white}textarea{min-height:90px}button{font:inherit;padding:10px 16px;margin:8px 8px 8px 0;cursor:pointer}nav a{display:inline-block;margin:5px 14px 5px 0}small{color:#536477}.note{border-left:4px solid #a27738;padding-left:16px}@media(max-width:760px){main{padding:14px}.pair,.fields{grid-template-columns:1fr}}@media print{body{background:white}main{padding:0}.card{break-inside:avoid}.pair{grid-template-columns:1fr 1fr}button{display:none}details{display:block}}'''
def page(title,body,js=''):return '<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+e(title)+'</title><style>'+CSS+'</style><body data-dataset="derm7pt-release_v0-source-review"><script id="concept-ids" type="application/json">[]</script><main>'+body+'</main>'+('<script>'+js+'</script>' if js else '')+'</body></html>'

def main():
 B.mkdir(exist_ok=True)
 for folder in ('raw','images','figures','sources'):
  shutil.copytree(D/folder,B/folder,dirs_exist_ok=True)
 for snapshot in (B/'sources').glob('*.html'):
  snapshot.rename(snapshot.with_suffix('.html.txt'))  # Source snapshots are downloads, not offline runtime pages.
 for name in ('verification.json','parser-reconciliation.json','nine-pairs.json','nine-pairs.csv','all-records-index.csv','case-id-empty-index.csv','case-id-present-index.csv','manual-review.csv','scope-impact.csv'):
  shutil.copyfile(D/name,B/name)
 for name in ('audit_derm7pt_observations.py','build_derm7pt_observation_review.py'):
  shutil.copyfile(ROOT/'scripts'/name,B/name)
 v=read('verification.json');pairs=read('nine-pairs.json');allrows=csvrows('all-records-index.csv');scopes=csvrows('scope-impact.csv');raw=(D/'raw/meta.csv').read_text().splitlines()
 sources=[dict(id='S1',description='Original release_v0 ZIP: README, meta.csv, official split CSVs, nine selected image members',location='raw/meta.csv; raw/nine-original-lines.txt; raw/README.txt',authority='User-supplied archive; matches Slurm ZIP and CSV hashes'),dict(id='S2',description='Original Slurm image audit and parser',location='job28734478; commit83972e99763ef6ecaebba3cbad6c0bf14e62e63a; hpc/derm7pt_audit.py:40-66,89-98,118-135',authority='Execution evidence'),dict(id='S3',description='Independent two-reader reconciliation of all 19 columns',location='audit_derm7pt_observations.py; verification.json; parser-reconciliation.json',authority='Current local audit; source SHA256 and execution Git HEAD recorded'),dict(id='S4',description='Official paper: Section II p2 defines case as unique lesion; Section III p4 reports four missing clinical images replaced with dermoscopy',location='sources/official-paper.pdf#page=4',url='https://www.cs.sfu.ca/~hamarneh/ecopy/jbhi2018a.pdf',authority='Dataset authors; does not define CSV case_id'),dict(id='S5',description='Pinned official loader: constructor109-146, get_img_paths336-356, image filenames388-400; directly uses derm/clinic columns, .iloc split indices; no case_id join/fallback',location='sources/official-dataset.py',url='https://github.com/jeremykawahara/derm7pt/blob/ce436877573c0a53cfa0d224bda20d9479b795aa/derm7pt/dataset.py#L336',authority='Author code'),dict(id='S6',description='Official README, web-image notebook, public welcome/download pages and issue/PR listing (14 items, eight actual issues), issue11 comment',location='sources/',url='https://github.com/jeremykawahara/derm7pt/issues/11',authority='Issue11 reply is a non-maintainer comment, NOT author confirmation')]
 (B/'sources-receipt.json').write_text(json.dumps(sources,ensure_ascii=False,indent=2)+'\n')
 body='<nav><a href="../../index.html">← 主报告 / Main report</a><a href="#pairs">9 个病例 / Nine cases</a><a href="#identity">身份字段 / Identity</a><a href="#impact">方案影响 / Impact</a><a href="#sources">证据 / Sources</a></nav>'
 body+='<h1>Derm7pt：原始记录核查与人工审阅<br><span class="en">Source-record verification & manual review</span></h1>'
 body+='<p>MED26-006 · 私有 / Private · '+e(v['created_at'])+'</p><div class="banner"><b>观察成立，不认定为数据错误 / Observations confirmed, not classified as data errors.</b><p>独立读取核实 9 个病例在原始 CSV 中的 derm 与 clinic 字段相同；984/1011 个 case_id 为严格空字符串，27 个非空。全部原始字段与已收集 Slurm 输出一致。未发现导致这两项观察的解析错误。</p><p class="en">Nine source rows reference the same file for both roles; 984/1011 case_id fields are exactly empty and 27 are populated. All original cells agree with the collected Slurm export. No parser defect causing these observations was found.</p><p><b>更正 / Correction:</b> 9 条原始 notes 全部记录了 clinic→derm 替代。4 条明确临床图缺失，论文第4页也说明了4例此类替代；另5条注明被替代路径，原因未详述。此前“原因未知”的笼统判断不够完整。<br><span class="en">All nine original notes document clinic→derm replacement. Four explicitly identify missing clinical images, consistent with paper p4. Five name the replaced paths without explaining why. The earlier blanket “cause unknown” statement was incomplete.</span></p></div>'
 body+='<h2>证据链与解析复核 / Provenance & parser reconciliation</h2>'
 body+=tab(['项目 / Item','值 / Value'],[(e(k),'<code>'+e(v[k])+'</code>') for k in ['archive','archive_bytes','archive_sha256','local_archive','original_csv_zip_member','original_csv_sha256','actual_slurm_csv_path','rdm_recovery_zip','slurm_job','slurm_audit_commit','independent_script_sha256','local_git_head']])
 body+='<p>本轮未访问 Bunya 文件系统、未提交新 Slurm 作业、未执行模型。读取本地同哈希 ZIP，并复用 28734478 的已验收 CSV／图片清单。实际 scratch CSV 路径如上；原始 RDM ZIP 保持不变。<br><span class="en">No new remote inspection/job or model execution. This review reads the local byte-identical ZIP and reuses the accepted job28734478 records; the actual prior scratch CSV path is listed above.</span></p>'
 body+='<p>独立方式 A：验证 CSV 不含引号、每物理行恰好19字段后，直接按 UTF-8 行和逗号拆分。方式 B：pandas C 引擎，全部按字符串读取，关闭 NA 推断。两者逐单元格一致，且与原 csv.DictReader 输出全部 19,209 个原始字段一致。按原始行序核对 official split、路径、case_num、case_id、诊断；不按空 case_id 关联，不补默认值、不改变大小写。<br><span class="en">Reader A uses literal lines/commas only after guarding no quotes and exactly19 fields per line. Reader B uses pandas C CSV parsing with string dtype and NA inference disabled. All19,209 cells agree with each other and the original DictReader export. Row-index, split, paths and labels agree; no case_id join, default replacement or case folding is used.</span></p>'
 body+='<nav><a href="verification.json">核查 JSON</a><a href="parser-reconciliation.json">解析对应 / Reconciliation</a><a href="raw/meta.csv">原始 CSV / Original</a><a href="audit_derm7pt_observations.py">核查脚本 / Audit script</a><a href="review_checks.ipynb">复查 notebook / Companion</a></nav>'
 body+='<h2 id="pairs">全部 9 个病例 / All nine cases</h2><p>纳入规则：原始 derm 字符串严格等于 clinic；全部纳入，按原始行序。图片直接从已验哈希 ZIP 导出，原分辨率、原字节、不裁剪。点击任一图查看原尺寸。<br><span class="en">Selection: exact field-string equality, all matches in source order. Images are original ZIP bytes at native resolution; no crop. Click to open the original.</span></p>'
 body+=tab(['case_num','CSV 行 / Line','原始索引 / Index0','split','case_id','原始相同路径 / Same raw path','原始 notes / Notes'],[(f'<a href="#{r["review_id"]}">{e(r["case_num"])}</a>',r['csv_physical_line'],r['row_index_zero_based'],e(r['official_split']),e(r['case_id']) or '<i>空 / Empty</i>',e(r['derm']),e(r['notes'])) for r in pairs])
 body+='<p><b>相同性定义 / Equality:</b> 9/9 字段字符串相同 → 同一 scratch 路径和同一 ZIP 成员 → 同一文件字节和解码像素。这里没有“两份不同文件恰好相同”的证据；全审计中未发现不同路径的字节哈希重复。像素相同不能证明模态标签合适，也不能替代临床审阅。<br><span class="en">9/9 have identical strings, resolved paths and ZIP members, so both roles read one file with identical bytes/pixels. These are not two different files that happen to match. Modality suitability remains a human-review question.</span></p><nav><a href="nine-pairs.csv">完整9例索引 CSV</a><a href="raw/nine-original-lines.txt">原始行 / Raw lines</a><a href="manual-review.csv">可填写审阅 CSV / Review template</a></nav>'
 body+='<div class="banner"><b>人工审阅 / Human review</b><p>所有项目初始“未审阅”，没有 AI 图像类型或临床正确性判断。填写不改变输入。浏览器自动保存仅为便利，请导出 JSON 留存；若本地存储不可用，使用导出或 CSV。<br><span class="en">All items begin unreviewed; no AI image-type or clinical-correctness labels. Review does not change inputs. Export JSON for durable records; CSV is available without JavaScript.</span></p><button id="export">导出审阅 / Export JSON</button><label>导入已保存审阅 / Import saved review<input id="import" type="file" accept=".json"></label><p id="storage" role="status"></p></div>'
 for r in pairs:
  rid=r['review_id'];body+='<article class="card" id="'+rid+'"><h3>'+rid+'</h3><p><span class="tag">同一文件 / SAME FILE</span> <span class="tag">未审阅 / Unreviewed until recorded</span></p>'
  body+='<p>原始 CSV 第 '+str(r['csv_physical_line'])+' 行（表头第1行）；数据行 '+str(r['data_row_one_based'])+'；零基索引 '+str(r['row_index_zero_based'])+'；'+e(r['official_split'])+'。原始诊断 / Source diagnosis: '+e(r['diagnosis'])+'</p>'
  body+='<div class="pair">'+''.join('<figure><a href="'+r['display_image']+'" target="_blank"><img src="'+r['display_image']+'" width="'+str(r['width'])+'" height="'+str(r['height'])+'" alt="Case '+r['case_num']+' '+role+' role; same source file"></a><figcaption>'+role+' 字段 / field: '+e(r[role])+'</figcaption></figure>' for role in ('derm','clinic'))+'</div>'
  body+='<p><b>原始 notes:</b> '+e(r['notes'])+'</p><p><a href="'+r['pair_figure']+'">2640×1408 并排图 / Pair figure</a> · <a href="records.html#row-'+str(r['csv_physical_line'])+'">完整原始记录 / Full original record</a></p>'
  body+='<details><summary>身份、路径与哈希 / Identity, paths & hashes</summary><pre>'+e(json.dumps({k:r[k] for k in ['case_num','case_id','derm','clinic','derm_resolved_path','clinic_resolved_path','derm_sha256','clinic_sha256','derm_pixel_sha256','clinic_pixel_sha256']},ensure_ascii=False,indent=2))+'</pre></details><div class="fields">'
  fields={'derm_image_type':('derm 图片类型 / Image type',['未审阅 / Unreviewed','皮肤镜 / Dermoscopic','临床照片 / Clinical','其他 / Other','无法判断 / Cannot determine']),'clinic_image_type':('clinic 图片类型 / Image type',['未审阅 / Unreviewed','皮肤镜 / Dermoscopic','临床照片 / Clinical','其他 / Other','无法判断 / Cannot determine']),'assessable':('是否可判断 / Assessable',['未审阅 / Unreviewed','可以 / Yes','部分 / Partly','无法 / No']),'obvious_input_anomaly':('明显输入异常 / Obvious input anomaly',['未审阅 / Unreviewed','未见明显异常 / None apparent','疑似，需说明 / Suspected; explain','无法判断 / Cannot determine']),'status':('审阅状态 / Review status',['UNREVIEWED','REVIEWED_PENDING_DECISION','REVIEWED'])}
  for key,(label,opts) in fields.items():body+='<label>'+label+'<select data-case="'+rid+'" data-field="'+key+'">'+''.join('<option>'+e(opt)+'</option>' for opt in opts)+'</select></label>'
  for key,label in [('reviewer','审阅者 / Reviewer'),('reviewed_at','日期 / Date')]:body+='<label>'+label+'<input data-case="'+rid+'" data-field="'+key+'"></label>'
  for key,label in [('evidence_and_example_id','判断依据与示例 ID / Evidence & example ID'),('suggested_action','处理建议（不自动执行）/ Suggested action (not executed)')]:body+='<label>'+label+'<textarea data-case="'+rid+'" data-field="'+key+'"></textarea></label>'
  body+='</div></article>'
 body+='<h2 id="identity">case_id 与身份层级 / case_id & identity levels</h2><p>字段位于第18列，每行均有该字段。缺失定义仅为原始字段长度为0：984/1011（97.33%）；非空27个，均不同。空格专有值0、NaN/null/none/NA/N/A 哨兵0。未以 pandas 默认 NaN 作判定。<br><span class="en">Column18 is present in every row. Missing means exactly zero characters:984/1011(97.33%);27distinct nonempty values. No whitespace-only or listed NA sentinel values. No default pandas NA conversion is used.</span></p>'
 body+=tab(['身份层级 / Level','已验证 / Verified','不能据此推断 / Not established'],[('文件 / File','原始相对路径＋文件/像素哈希；derm1011个不同文件 / Original path + hashes;1011distinct derm files','不同文件≠不同病灶或患者 / Different files do not prove distinct lesions/patients'),('病例记录 / Case row','case_num1011个唯一值；原始行与标签可追溯 /1011unique case_num values; traceable rows/labels','行号是定位工具，不是患者 ID / Row number is a locator, not patient ID'),('病灶 / Lesion','作者论文第2页将一个 case 定义为一个独特病灶 / Paper p2 defines a case as a unique lesion','这是作者单位定义；尚无独立的跨病例/跨数据集病灶匹配审计 / Author unit definition, not independent cross-case/dataset linkage audit'),('case_id 字段','27个原样字符串，984空 /27literal strings,984empty','查阅范围未找到该列的正式语义/生成规则；不能当患者键 / No formal field definition/generation rule found; not a patient key'),('患者 / Patient','有 sex、location 等描述列，没有已验证的患者关联键 / Descriptive sex/location; no verified patient linkage key','不得用文件名、行号、case_num、case_id 或看图宣称患者独立 / No patient independence from names, row IDs, case IDs or visual inspection')])
 body+='<nav><a href="records.html">完整1011行可浏览索引 / Full index</a><a href="case-id-empty-index.csv">984空值完整 CSV</a><a href="case-id-present-index.csv">27非空完整 CSV</a><a href="all-records-index.csv">全部原始字段＋路径 / Full fields & paths</a><a href="raw/raw-examples.txt">原始缺失／非缺失示例 / Raw examples</a></nav><pre>'+e((D/'raw/raw-examples.txt').read_text())+'</pre>'
 body+='<h2 id="impact">derm-only 的实际影响 / Impact on derm-only</h2><p><b>已验证 / Verified:</b> 每病例取一次 derm 时，1011记录对应1011个不同路径、文件哈希和解码像素哈希。九例同图引用发生在同一病例的两个角色之间，未造成两条 derm 样本重复，也未发现路径／标签错配。数据完整性通过不代表所有模态和临床标签已获人工确认。<br><span class="en">One derm input per row yields1011distinct paths, byte hashes and pixel hashes. The nine cross-role aliases do not duplicate derm samples or cause an observed path/label mismatch. Integrity acceptance does not certify modality or clinical label correctness.</span></p><p><b>范围是条件计数，不是选样决策 / Conditional counts, not sampling decisions:</b> Derm7pt目标诊断合并与官方test/更大探索队列尚未冻结。下表说明不同既有候选范围是否涉及九例；本轮没有删除或纳入新样本。源域 DermaMNIST 的固定70张测试图是另一数据集，勿混淆。<br><span class="en">Target diagnostic grouping and official-test versus exploratory scope remain unfrozen. The table audits candidate scopes without selecting samples. The70-image source DermaMNIST test set is a different dataset.</span></p>'
 body+=tab(['split','条件诊断范围 / Conditional diagnosis scope','病例 / Cases','九例交集 / Alias cases','case_id空 / Empty','相关case_num'],[(e(x['split']),e(x['diagnosis_rule']),x['cases'],x['same_role_path_cases'],x['case_id_empty'],e(x['affected_case_nums']) or '—') for x in scopes])
 body+='<p>可继续：原图/标签对应核查、图片级描述统计、人工概念与图像审阅；在模型与评价协议另获批准后，可报告明确队列上的图片/病例级描述性表现。<br><span class="en">Can proceed: image-label mapping checks, descriptive image statistics and manual review; after separate model/protocol approval, descriptive image/case-level performance on a declared cohort.</span></p><p>需要限制：不能把 clinic 与 derm 当作独立样本或九例独立双视图；未建立患者关联时，不能宣称患者隔离、独立患者样本量或患者级推广置信区间。病例级 bootstrap/显著性推断如使用，必须显式声明病例独立假设未经患者键验证。不能把缺 case_id 的行全部归成一个患者，也不能为每行补一个患者号。<br><span class="en">Limits: roles are not independent samples, and these nine are not distinct paired views. No claim of patient-disjoint cohorts, independent-patient N or patient-level generalization intervals. Case-level inferential procedures require an explicitly unverified independence assumption; do not group all blank IDs as one patient or invent one patient ID per row.</span></p>'
 body+='<h2 id="sources">已知、未知与来源 / Evidence & unresolved questions</h2><p>直接事实：九行同路径和原始替代备注、四例缺图描述、984个原始空字符串；两种独立读取与Slurm解析一致。可能解释：另五条也可能是发布整理时的替代，但理由未知，不能推断原clinic损坏或derm标错。仍未知：case_id语义/稀疏原因、另五条替代动机、患者关联与跨数据集重叠、每例人工模态审阅。<br><span class="en">Facts: source aliases/replacement notes, four explicit missing-clinical cases and984literal blanks; independent parsing agrees. Unproven possibility: the additional five substitutions reflect release curation; no claim that original clinic files were corrupt or derm labels wrong. Unknown: field semantics/sparsity reason, five substitution motives, patient/cross-dataset linkage and manual modality judgements.</span></p><p>查找范围：ZIP README及原始notes；固定提交的作者README、dataset.py、web_images notebook；论文第2与4页；官方网站；当前14个issue/PR条目及与数量相关的#11回复。#11回复是非维护者，不作为作者解释。上述材料未找到case_id正式定义；这不等于作者从未提供。<br><span class="en">Search scope: archive README/notes, pinned author README/loader/web notebook, paper pp2/4, official site,14issue/PR entries and relevant#11 reply. That reply is not from a maintainer. No formal case_id definition found within this scope; not a claim that none was ever supplied.</span></p>'
 body+='<ul>'+''.join('<li>'+e(x['id']+': '+x['description'])+'<br><code>'+e(x['location'])+'</code>'+(' · <a href="'+e(x['url'])+'">公开原始来源 / Public source</a>' if x.get('url') else '')+'</li>' for x in sources)+'</ul><p><a href="sources/official-paper.pdf#page=4">论文离线副本，第4页 / Offline paper p4</a> · <a href="sources-receipt.json">来源记录 / Source receipt</a> · <a href="bundle-manifest.json">完整文件哈希 / File hashes</a></p><p class="note">本轮没有需要你批准的数据修正。九例图像类型和明显输入异常仍待人工填写；不自动把审阅意见用于删图或改样本。/ No data correction needs approval now. Manual image-type/anomaly review remains open; review entries never automatically change inputs.</p>'
 js='''const key='humcd-derm7pt-release-v0-MED26-006-review-v1';const fields=[...document.querySelectorAll('[data-case]')];const msg=document.getElementById('storage');function snapshot(){let rows={};for(const f of fields){(rows[f.dataset.case]??={})[f.dataset.field]=f.value}return {schema:1,dataset:'Derm7pt-release_v0',rows}}function apply(x){if(x.schema!==1||x.dataset!=='Derm7pt-release_v0'||!x.rows)throw Error('Wrong review identity');for(const f of fields){let v=x.rows[f.dataset.case]?.[f.dataset.field];if(typeof v==='string'){if(f.tagName==='SELECT'&&![...f.options].some(o=>o.value===v))throw Error('Unknown choice');f.value=v}}}try{let s=localStorage.getItem(key);if(s)apply(JSON.parse(s));msg.textContent='本机保存可用；请导出留存 / Local saving available; export for durable records.'}catch(e){msg.textContent='本地保存不可用；请导出或使用CSV / Local storage unavailable; export or use CSV.'}for(const f of fields)f.addEventListener('change',()=>{try{localStorage.setItem(key,JSON.stringify(snapshot()))}catch(e){msg.textContent='保存失败；请导出 / Save unavailable; export.'}});document.getElementById('export').onclick=()=>{let u=URL.createObjectURL(new Blob([JSON.stringify(snapshot(),null,2)],{type:'application/json'}));let a=document.createElement('a');a.href=u;a.download='derm7pt-manual-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};document.getElementById('import').onchange=async e=>{try{apply(JSON.parse(await e.target.files[0].text()));msg.textContent='已导入；请导出留存 / Imported; export to keep.'}catch(x){msg.textContent='导入未完成，请核对文件 / Import failed; check file.'}};'''
 (B/'index.html').write_text(page('Derm7pt source observations | 原始观察核查',body,js))
 recordbody='<nav><a href="index.html">← 核查审阅 / Review</a><a href="all-records-index.csv">CSV</a></nav><h1>1011 原始记录索引 / Full original-record index</h1><p>原始物理行号包括表头；空字符串显示∅，仅用于显示，没有补值。可用浏览器查找case_num、路径或ID。/ Physical line includes header; ∅ displays a literal empty field, not a replacement value. Use browser Find.</p>'
 recordbody+=tab(['CSV行 / line','case_num','case_id','split','derm','clinic','notes','原始行 / Raw line'],[(f'<span id="row-{r["csv_physical_line"]}">{r["csv_physical_line"]}</span>',e(r['case_num']),e(r['case_id']) or '∅',e(r['official_split']),e(r['derm']),e(r['clinic']),e(r['notes']),'<details><summary>原文 / Raw</summary><pre>'+e(raw[int(r['csv_physical_line'])-1])+'</pre></details>') for r in allrows])
 (B/'records.html').write_text(page('Derm7pt full record index',recordbody))
 cells=[{'cell_type':'markdown','metadata':{},'source':['# Derm7pt observation review\nCompanion for independently checking saved raw rows and counts. No model or remote access. The complete executed audit is in audit_derm7pt_observations.py. Notebook not executed during delivery.']},{'cell_type':'code','metadata':{},'execution_count':None,'outputs':[],'source':["from pathlib import Path\nimport json\np = Path('.')\nraw=(p/'raw/meta.csv').read_text()\nassert '\"' not in raw\nlines=raw.splitlines(); header=lines[0].split(',')\nrows=[dict(zip(header, line.split(','))) for line in lines[1:]]\nassert all(len(line.split(','))==19 for line in lines)\nlen(rows), sum(r['case_id']=='' for r in rows), sum(r['derm']==r['clinic'] for r in rows)"]},{'cell_type':'code','metadata':{},'execution_count':None,'outputs':[],'source':["[(i+2,r['case_num'],r['derm'],r['clinic'],r['notes']) for i,r in enumerate(rows) if r['derm']==r['clinic']]"]}]
 (B/'review_checks.ipynb').write_text(json.dumps(dict(nbformat=4,nbformat_minor=5,metadata={'kernelspec':{'display_name':'Python 3','language':'python','name':'python3'}},cells=cells),indent=2)+'\n')
 manifest={str(p.relative_to(B)):hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(B.rglob('*')) if p.is_file() and p.name!='bundle-manifest.json'}
 (B/'bundle-manifest.json').write_text(json.dumps(dict(id='derm7pt-observation-review',dataset_id='derm7pt-release_v0-source-review',entry='index.html',created_at=datetime.now(timezone.utc).isoformat(),files=manifest),indent=2)+'\n')
 print('Built private bundle:',B,'files',len(manifest))
if __name__=='__main__':main()
