"""Incremental evidence/status overlay in the existing private report; no fabricated results."""
import json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
O=ROOT/'artifacts/bunya/next-phase-20260921'
W=ROOT/'artifacts/bunya/evaluation-baselines-20260910'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()

def main():
 status=json.loads((O/'status.json').read_text());p=W/'workstream_status.json';data=json.loads(p.read_text())
 if not (O/'workstream_status.before.json').exists():(O/'workstream_status.before.json').write_bytes(p.read_bytes())
 summary=data['research_summary'];summary['paragraphs']=[x for x in summary['paragraphs'] if not x.get('next_phase_20260921')]
 submitted=status.get('submitted_jobs',[])
 text={'zh':'下一阶段（2026-09-21）：A最终输入掩码敏感性、B医学迁移。下方既有结果仍为已验收；新工作线的准备不代表模型运行。A已核对500图/5687区域（413原零特征，5274原有效），候选5条件28435条记录，几何预检查r2有6空mask；没有新模型推理。B精确Zenodo档案仍未验收，melanoma元数据训练1021图/533病灶、测试70图/61病灶；Derm7pt实际标签计数未知。协议／预算等待用户明确选择，不将推荐当批准。',
 'en':'Next phase (2026-09-21):A final-input mask sensitivity; B medical transfer. Existing results below remain accepted; new-workstream preparation is not model execution. A verified500 images/5687regions (413original zeros,5274valid), candidate5conditions28435records, geometry-only r2 preview6empty masks; no new inference. B exact Zenodo archive remains unaccepted; melanoma metadata has1021training images/533lesions and70test images/61lesions. Actual Derm7pt sign counts are unknown. Protocol/resource recommendations await explicit user decisions.'}
 if status['authorizations'].get('A'):
  text={'zh':'下一阶段：A五条件协议和资源上限已批准；10类新执行路径的缓存得分／分配检查通过，GPU不变区域对照仍是逐类运行门槛。B已批准病灶优先400病灶各1图，名单须待图像、模型及预算确认后冻结。Derm7pt已提供RDM原始ZIP，Slurm复制到scratch并审计；医学训练未批准。用户要求先澄清已有DermaMNIST corrected版本身份，暂不下载数据。已有全部复现结果保持已验收状态。',
        'en':'Next phase: A five conditions and resource caps are approved. The new score/assignment path passed all ten saved-cache checks; GPU unchanged-mask controls remain mandatory per-class gates. B lesion-first sampling (400 distinct lesions, one image each) is approved, with list freezing conditional on image/model/budget acceptance. Derm7pt RDM ZIP is available for Slurm staging/audit on scratch. Medical training is not approved. DermaMNIST downloads are on hold while the existing corrected-release identity is clarified. All earlier accepted replication results remain unchanged.'}
 if status.get('exact_data_preparation'):
  e=status['exact_data_preparation']
  text={'zh':'A五条件实验保持原批准与提交状态，尚未收集验收。B仅新增精确Zenodo12739457数据准备授权（1CPU/8GiB/2小时）：先检查已有文件，有完整匹配文件则复用，否则单次下载；审计通过后归档Q9903并发布scratch工作路径，不授权模型实验。Derm7pt28731216已确认因Q9903路径Permission denied失败，未复制/解压，未重提。精确发布任务='+e['job_id']+'，状态='+e['status']+'；归档状态='+e['archive_status']+'。旧版文件和全部既有已验收复现结果保留。',
        'en':'A retains its original approved submissions; no new results have been collected/accepted. B now authorizes exact Zenodo12739457 data preparation only (1CPU/8GiB/2h): check/reuse complete existing files first, otherwise one download, then audit before Q9903 archival and scratch path publication. No model experiment is authorized. Derm7pt28731216 failed with Q9903 path Permission denied before copy/extraction; no retry. Exact-release job='+e['job_id']+', state='+e['status']+'; archival='+e['archive_status']+'. Existing OneDrive files and all previously accepted replication results are preserved.'}
  if e.get('verified_node'):
   text['zh']+=' 用户已确认HPC/账号权限；只读诊断28733281在bun148实际列目录成功，当前首次获取任务已绑定该节点。两次先前拒绝访问均在bun147，具体挂载/群组原因未定；不把读访问成功等同于归档成功。'
   text['en']+=' User confirmed HPC/account permissions; read-only diagnostic28733281 successfully listed the collection on bun148, and the first-acquisition task is bound to that node. Both earlier denials were on bun147; the precise mount/group cause is unproven. Read access is not archival acceptance.'
  if e.get('received_bytes')==0 and e.get('download_attempts')==1:
   text['zh']+=' 实际获取28733630已结束：RDM父目录/锁文件创建成功；唯一HTTP请求返回504、收到0字节。配套CSV已核验复用，未执行NPZ数组审计、未归档原始数据、未发布可用路径；不重试，等待用户选择本地下载或暂停。'
   text['en']+=' Acquisition28733630 has ended: RDM parent/lock creation succeeded; the sole HTTP request returned504 with0bytes. Companion CSV was verified/reused. No NPZ array audit, raw-data archival or ready-path publication occurred. No retry; await user choice of local download or pause.'
 derm=status.get('derm7pt',{})
 if derm.get('previous_failed_job'):
  text['zh']=text['zh'].replace('Derm7pt28731216已确认因Q9903路径Permission denied失败，未复制/解压，未重提。','Derm7pt28731216的历史访问失败保留，最新进展见下段。')
  text['en']=text['en'].replace('Derm7pt28731216 failed with Q9903 path Permission denied before copy/extraction; no retry.','The historical Derm7pt28731216 access failure is preserved; see the latest update below.')
  text['zh']+=' Derm7pt最新：用户在Slurm交互作业实际读取ZIP成功（仅确认读取）。本次授权恢复作业'+derm['job_id']+'，状态='+derm['state']+'；验收='+derm['acceptance']+'；后续='+derm['retry_status']+'。28734311启动失败是助手误填launcher哈希（MED26-005），发生在访问数据之前，与ZIP质量或RDM权限无关。修正配置已准备；未获明确重提许可前不提交。'
  text['en']+=' Latest Derm7pt: user successfully opened/read the ZIP in interactive Slurm (read access only). Newly authorized staging job '+derm['job_id']+', state='+derm['state']+'; acceptance='+derm['acceptance']+'; next='+derm['retry_status']+'. Job28734311 failed before data access because the assistant supplied the wrong launcher hash (MED26-005), unrelated to ZIP quality or RDM permissions. Corrected configuration is prepared; resubmission awaits explicit approval.'
  if derm.get('job_id')!='28734311':
   text['zh']=text['zh'].replace('修正配置已准备；未获明确重提许可前不提交。','用户已明确批准修正后重提一次，28734478已提交；不授权后续自动重试。')
   text['en']=text['en'].replace('Corrected configuration is prepared; resubmission awaits explicit approval.','User explicitly approved one corrected resubmission,28734478; no further automatic retry is authorized.')
  if derm.get('acceptance')=='PASS_DATA_STAGING_ONLY':
   text['zh']+=' Derm7pt准备验收通过：28734478完成0:0/13秒，实际版本/运行入口校验通过；1011病例，官方训练/验证/测试413/203/395；2022条RGB图片角色记录对应2013个不同文件。9个病例的derm/clinic指向同一文件，984个case_id缺失；无跨划分完全相同像素组。这不证明患者或跨数据集独立；保留原始数据，医学模型协议未批准。'
   text['en']+=' Derm7pt staging accepted:28734478 completed0:0/13s with actual-version/runtime guards passed.1011cases, official train/valid/test413/203/395;2022RGB image-role records reference2013distinct files. Nine same-case derm/clinic aliases and984missing case_id values; no exact cross-split pixel groups. Patient/cross-dataset independence is not established. Originals preserved; medical model protocol remains unapproved.'
 if status.get('exact_data_preparation',{}).get('status')=='ACCEPTED_DATA_ONLY':
  text={'zh':'最新医学数据状态：复用用户Downloads精确文件，Slurm28738133完成0:0/37秒，发布MD5匹配，8215/573/1227划分及标签检查通过；Q9903独立版本归档、scratch工作路径和本地验收已完成。没有新HTTP下载。18对作者已知重复未跨当前划分，2组完全相同像素在训练内部；这不是与Derm7pt的重叠检查。Derm7pt28734478数据验收及9例人工审阅入口保留；case_id仅作为身份限制，不无证据重查。先前权限、launcher哈希和HTTP504失败完整保留。两条CSV读取ResourceWarning已记录，工程关闭句柄修复不改变结果，不重跑。没有医学模型运行授权。',
        'en':'Latest medical data: user Downloads exact file reused; Slurm28738133 completed0:0/37s with published MD5 and8215/573/1227split/label checks passed. Separate Q9903 archive, scratch paths and local data acceptance are complete. No new HTTP download.18author-known duplicate pairs do not cross current splits;2exact-pixel groups remain within training. This is not a Derm7pt overlap check. Accepted Derm7pt28734478 and nine-case manual review are preserved; case_id remains an identity limitation without repeated checks. Historical access, launcher-hash and HTTP504 failures remain. Two CSV ResourceWarnings are recorded; handle-closing cleanup changes no results and triggers no rerun. No medical model execution is authorized.'}
  summary['paragraphs'].insert(0,{'next_phase_20260921':True,'zh':'待选协议（推荐不是批准）：官方Derm7pt test按作者MEL为101例，排除转移性melanoma则100例；原始七项征象及作者分组保留。推荐101例、概念有效区域并集覆盖、完整12项/概念描述性对比，首轮不作显著性检验；regular pigmentation与streaks各仅1例。跨数据集重叠尚未审计；建议一次CPU数据核查上限4CPU/8GiB/30分钟/0GPU，待用户选择。公开SelfClean的Derm7pt内部近重复证据不能当跨数据集重叠，也未与本次9例建立对应。',
   'en':'Pending decisions (recommendations are not approval): official Derm7pt test has101author-grouped MEL cases, or100excluding metastasis. Preserve raw seven-sign categories and author grouping. Recommend101cases, union coverage of valid assigned regions, all12descriptive contrasts per concept and no first-pass significance testing; regular pigmentation and streaks each have only1case. Cross-dataset overlap remains unchecked; proposed one-off CPU data audit cap4CPU/8GiB/30min/0GPU awaits a decision. Published SelfClean within-Derm7pt near-duplicate evidence is not cross-dataset evidence and has not been identity-matched to our nine cases.'})
 text['next_phase_20260921']=True;summary['paragraphs'].insert(0,text)
 summary['paragraphs'].insert(1,{'next_phase_20260921':True,'zh':'新工作线实际状态：A='+status['A']+'；B='+status['B']+'；本批已提交作业='+str(submitted)+'。提交后仅一次调度核对，等待用户通知完成；不自动监控或重提。','en':'Actual new-workstream state:A='+status['A']+'; B='+status['B']+'; submitted jobs='+str(submitted)+'. One post-submission scheduler check; wait for user completion notification, no automatic monitor/retry.'})
 review=O/'derm7pt-review/bundle/bundle-manifest.json'
 if review.exists():
  summary['paragraphs'].insert(0,{'next_phase_20260921':True,'zh':'Derm7pt观察复核（MED26-006）：原始CSV与两种独立读取、既有Slurm解析全部一致。9个同路径病例均有原始用 derm 图替代 clinic 图备注；4例明确缺临床图且与论文第4页一致，另5例替代理由未详述。984个case_id严格为空、27个非空；字段语义未确认。1011个derm输入互不重复，不因同一病例跨角色引用产生重复样本。两项观察不认定为数据错误；图像适用性待人工审阅，下方专页提供全部9例原图对照、完整索引、原始行及审阅表。','en':'Derm7pt observations rechecked (MED26-006): all raw CSV cells agree across two independent readers and prior Slurm parsing. All9same-path cases have original replacement of clinic images with derm images notes;4explicit missing-clinical cases agree with paper p4, while5motives are unspecified.984case_id fields are exactly empty and27populated; field semantics remain unconfirmed.1011derm inputs are distinct; cross-role aliases do not duplicate derm-only samples. These observations are not classified as data errors. Human suitability review is pending; the linked page provides all9native-image pairs, full indexes, raw lines and review forms.'})
  summary['review_bundles']=[{'id':'derm7pt-review','manifest':str(review),'sha256':sha(review),'label':'Derm7pt 原始证据与9例人工审阅入口 / Derm7pt source evidence & nine-case manual review'}]
 summary['artifacts']=[a for a in summary['artifacts'] if 'next-phase-20260921' not in a['path']]
 for name,kind,label in [('A-workload.csv','table','A候选工作量与已有阶段耗时；未执行 / A proposed workload and prior measured stages; not executed'),('B-source-metadata-counts.csv','table','B源域元数据图片/病灶计数；不是图像验收 / B source metadata image/lesion counts, not image acceptance'),('current_ten_class_overview.csv','evidence','当前十类发现＋评价状态；历史发现表仍保留 / Current joined discovery/evaluation table; historic table preserved')]:
  f=O/name;summary['artifacts'].insert(0,dict(path=str(f),sha256=sha(f),kind=kind,caption=label))
 docs={str(Path(d['path']).resolve()):d for d in data['documents']}
 files=[(ROOT/'docs/NEXT_PHASE_READINESS_20260921.zh-en.md','下一阶段实际准备、待批协议与预算 / Next-phase readiness, pending decisions and budgets'),(O/'inventory/A-inventory.json','A全部区域身份及候选几何计数 / A complete region identity and candidate geometry counts'),(O/'status.json','A/B当前准备与提交状态 / Current A/B preparation/submission state'),(O/'B-sampling-feasibility.json','B图片/病灶抽样差异 / B image-versus-lesion sampling'),(O/'sources/release-download.json','精确发布获取证据 / Exact-release retrieval evidence')]
 for f,label in [(ROOT/'docs/NEXT_PHASE_EXECUTION_20260921.zh-en.md','已批准执行与corrected版本分歧 / Approved execution and corrected-release identity'),(O/'Downloads-DermaMNIST-C-identity.json','用户Downloads文件实际校验 / Actual user Downloads archive identity'),(O/'Derm7pt-local-zip-metadata.json','Derm7pt本地ZIP元数据，远端待审计 / Local Derm7pt ZIP metadata; remote audit pending'),(O/'submitted-batch.json','本批提交回执；非验收 / Batch submission receipts; not acceptance'),(O/'new-worker-cached-score-tests.json','A新执行路径缓存对照 / A new execution-path cached-score checks')]:
  if f.exists():files.append((f,label))
 for f,label in files:docs[str(f)]=dict(path=str(f),label=label,sha256=sha(f))
 for f,label in [(ROOT/'docs/DERMAMNIST_EXACT_PREPARATION_20260921.zh-en.md','精确医学数据准备授权与归档 / Exact medical data preparation and archival'),(O/'dermamnist-exact/submitted.json','精确数据准备提交回执 / Exact-release submission receipt'),(O/'dermamnist-exact/local-files.json','本地现有文件核对 / Existing local files')]:
  if f.exists():docs[str(f)]=dict(path=str(f),label=label,sha256=sha(f))
 collection=O/'dermamnist-exact/collections/28732647/20260921T045921.036585Z'
 for name,label in [('rdm_access.json','Q9903访问失败证据 / Q9903 access-failure evidence'),('existing_file_inventory.json','Slurm已有文件检查；RDM未知 / Slurm existing-file inventory; RDM unknown'),('collection.json','失败作业完整收集校验 / Complete failed-job collection integrity')]:
  f=collection/name
  if f.exists():docs[str(f)]=dict(path=str(f),label=label,sha256=sha(f))
 for f,label in [(O/'dermamnist-exact/verified-node-submitted.json','已验证节点首次获取提交 / First acquisition on verified node'),(O/'dermamnist-exact/access-diagnostic-collections/28733281/20260921T050347.536452Z/rdm_diagnostic.json','bun148实际访问诊断 / Actual bun148 access diagnosis')]:
  if f.exists():docs[str(f)]=dict(path=str(f),label=label,sha256=sha(f))
 failed=O/'dermamnist-exact/verified-node-collections/28733630/20260921T050725.304151Z'
 for name,label in [('dermamnist_corrected_224.npz.download.json','唯一下载尝试：504/0字节 / Sole download attempt:504/0bytes'),('existing_file_inventory.json','下载前完整文件核对 / Complete pre-download existing-file inventory'),('collection.json','获取失败的完整收集记录 / Complete acquisition-failure collection')]:
  f=failed/name
  if f.exists():docs[str(f)]=dict(path=str(f),label=label,sha256=sha(f))
 resume=O/'derm7pt-resumption'
 for name,label in [('launcher-correction.json','Derm7pt启动哈希修正及授权执行状态 / Derm7pt launcher correction and authorized execution status'),('collections/28734311/20260921T051307.668591Z/collection.json','Derm7pt历史启动失败收集范围 / Historical Derm7pt startup-failure collection scope'),('scheduler-after-submission.txt','Derm7pt旧失败作业调度状态 / Historical failed Derm7pt scheduler state'),('corrected-scheduler.txt','Derm7pt修正作业调度状态 / Corrected Derm7pt scheduler state'),('acceptance.json','Derm7pt数据准备验收 / Derm7pt data preparation acceptance')]:
  f=resume/name
  if f.exists():docs[str(f)]=dict(path=str(f),label=label,sha256=sha(f))
 for d in docs.values():d['sha256']=sha(Path(d['path']))
 review_doc=ROOT/'docs/DERM7PT_OBSERVATIONS_REVIEW_20260921.zh-en.md'
 if review_doc.exists():docs[str(review_doc)]=dict(path=str(review_doc),label='Derm7pt观察复核、原始依据与方案影响 / Derm7pt observation verification, raw evidence and scope impact',sha256=sha(review_doc))
 medical=O/'medical-decisions'
 for f,label in [(ROOT/'docs/DERM7PT_PROTOCOL_DECISIONS_20260921.zh-en.md','医学数据验收、重叠证据、范围/标签/统计/CPU预算待选表 / Accepted medical data, overlap evidence and pending protocol/budget choices'),(medical/'data-preparation/acceptance.json','精确DermaMNIST-C本地验收 / Exact DermaMNIST-C acceptance'),(medical/'accepted-dataset-paths.json','已验收RDM/scratch路径 / Accepted RDM and scratch paths')]:
  if f.exists():docs[str(f)]=dict(path=str(f),label=label,sha256=sha(f))
 for name,label in [('candidate-scopes.csv','Derm7pt候选范围实际计数；未冻结 / Actual candidate scope counts; not frozen'),('proposed-contrasts.csv','征象对比实际分母；协议未批准 / Actual contrast denominators; protocol unapproved'),('raw-sign-counts.csv','全部原始征象计数 / All raw sign counts')]:
  f=medical/name
  if f.exists():summary['artifacts'].append(dict(path=str(f),sha256=sha(f),kind='table',caption=label))
 current=ROOT/'artifacts/bunya/next-phase-20260922'
 if (current/'context-reconciliation.json').exists():
  for paragraph in summary['paragraphs']:
   if paragraph.get('next_phase_20260921'):
    paragraph['zh']=paragraph.get('zh','').replace('图像适用性待人工审阅','用户已完成9例基础视觉审阅，专业成像类型及临床标签未确认')
    paragraph['en']=paragraph.get('en','').replace('Human suitability review is pending','User basic visual review of all nine is recorded; professional modality/clinical validation remains open')
  summary['paragraphs'].insert(0,{'next_phase_20260921':True,'zh':'2026-09-22实际核对：A十作业全部结束，6COMPLETED、4FAILED（Airliner、Hummingbird、Container Ship、Beach Wagon），仅调度状态已核实，尚未收集/验收，失败原因未知；不自动重提。两个医学数据集准备已验收。用户9例基础视觉审阅已记录：均正常显示、未见明显损坏/无关内容，像皮肤镜仅为非专业初步印象；未审标签/身份/跨数据集重叠，不代表1011例全审。录入9月22日，实际审阅日未知，无删改要求。H/R/S/M均仍待明确选择；新模型训练或推理未获授权。',
   'en':'2026-09-22 actual refresh: all ten A jobs ended, six COMPLETED and four FAILED (Airliner, Hummingbird, Container Ship, Beach Wagon). Scheduler status only; results uncollected/unaccepted and failure causes unknown; no automatic retry. Both medical datasets are accepted. User basic visual review of nine cases is recorded: normal display, no obvious corruption/unrelated content; dermoscopic appearance is a preliminary non-expert impression. Labels/identity/cross-dataset overlap were not reviewed; this is not a1011-case review. Entered22September, actual review date unknown, no modification requested. H/R/S/M still await explicit choices; new medical training/inference is unauthorized.'})
  summary['paragraphs'].insert(1,{'next_phase_20260921':True,'zh':'医学ResNet50提案M区分用途：全部8215图训练七类分类器，573图选模型，冻结后1227图最终测试；400不同病灶各1图仅用于后续概念发现。候选标准R50/固定ImageNet初始化、seed43、batch64、50epochs、Adam1e-4；上限1L40S/4CPU/16GiB/4小时/5GiB，并非实测。专用实现及新模型映射检查仍待完成，当前不是可执行训练作业。',
   'en':'MedicalResNet50 proposal M separates roles: all8215images train the seven-class classifier,573select the checkpoint,1227form final test after freezing;400distinct-lesion images serve later concept discovery only. Proposed standardR50/pinnedImageNet initializer,seed43,batch64,50epochs,Adam1e-4; cap1L40S/4CPU/16GiB/4h/5GiB, not measured throughput. Dedicated implementation/new-model mapping checks remain outstanding; this is not an executable training job.'})
  if (current/'rationale/decision-rationale.json').exists():
   summary['paragraphs'].insert(0,{'next_phase_20260921':True,'zh':'决策依据补充：用户明确H/R/S/M尚未批准。MEL与征象分组有作者代码依据；覆盖面积及12项对比是本项目候选分析规则。单次训练与50epochs仅为预算选择，没有代表性/收敛充分性证据；作者默认100epochs、batch128，启动脚本循环3次。已批准选样seed43不等于批准分类器训练seed43。集中决定表及英文Implementation Notes已按稳定ID逐项说明替代与解释边界；本轮无实验。',
    'en':'Rationale clarification: user explicitly has NOT approved H/R/S/M. MEL/sign mappings are source-backed; coverage and twelve contrasts are proposed project analyses. One classifier fit and fifty epochs are budget choices, without evidence of representativeness or convergence sufficiency; author defaults are100epochs/batch128 and three launcher repetitions. Approved discovery-sampling seed43 does not approve classifier-training seed43. Stable-ID rationale, alternatives and limitations are in the decision table and English Implementation Notes. No experiment was run for this update.'})
  for f,label in [(ROOT/'docs/NEXT_PHASE_CURRENT_DECISIONS_20260922.zh-en.md','9月22日实际状态、批准边界及H/R/S/M集中决定 / Current state, authority boundaries and H/R/S/M decisions'),(ROOT/'docs/MEDICAL_RESNET50_PROPOSAL_20260922.zh-en.md','医学ResNet50具体提案：数据用途、参数、依据和预算 / MedicalResNet50 roles, configuration, evidence and budget'),(current/'authorization-ledger.json','原始决定与授权边界 / Explicit decisions and authority ledger'),(O/'derm7pt-review/user-review-20260922.json','用户9例基础视觉审阅及限制 / User nine-case basic visual review and limits'),(current/'M-resnet50.proposed.json','M待批机器配置，非执行作业 / M proposed config, not an execution job')]:
   docs[str(f)]=dict(path=str(f),label=label,sha256=sha(f))
  summary['artifacts']=[a for a in summary['artifacts'] if 'next-phase-20260922' not in a['path']]
  f=current/'A-current-status.csv';summary['artifacts'].insert(0,dict(path=str(f),sha256=sha(f),kind='table',caption='A实时调度终态：不是验收 / A final scheduler states: not acceptance'))
  preparation=current/'preparation'
  if (preparation/'code-receipt.json').exists():
   for paragraph in summary['paragraphs']:
    if paragraph.get('next_phase_20260921'):
     paragraph['zh']=paragraph.get('zh','').replace('专用实现及新模型映射检查仍待完成，当前不是可执行训练作业。','专用实现与本地软件检查已完成；新模型GPU映射检查仍未执行，需明确批准及部署后才运行。')
     paragraph['en']=paragraph.get('en','').replace('Dedicated implementation/new-model mapping checks remain outstanding; this is not an executable training job.','Dedicated implementation and local software checks are complete; the new-model GPU mapping check remains unexecuted. Explicit approval and deployment are required before execution.')
   summary['paragraphs'].insert(0,{'next_phase_20260921':True,'zh':'最终推荐（尚未批准）：H＋R101＋S描述性＋M50轮/batch64/训练seed43。首轮解释一个冻结医学分类器，不验证跨训练seed稳定性；400病灶选样seed43与分类器seed是不同角色、不同授权。50/b64为410,750训练图次、6,450更新；100/b128为821,500图次、6,500更新。更新数接近不等于训练等价，50轮不是充分或最优长度。完整训练后先冻结validation所选checkpoint，再完成适配门槛和最终test；低分或曲线未收敛不自动延长，身份/非有限/重构问题阻断受影响验收。',
    'en':'Final recommendation, NOT APPROVED: H + R101 + descriptive S + M50epochs/batch64/training-seed43. This first round explains one frozen medical classifier, not cross-training-seed stability. Discovery-sampling seed43 and classifier seed have separate roles and authorization. 50/b64 gives410,750training visits/6,450updates;100/b128 gives821,500/6,500. Similar updates do not imply equivalent training;50epochs is not proven sufficient or optimal. Finish the schedule, freeze the validation-selected checkpoint, pass adapter checks, then final test. Low scores or apparent undertraining never trigger automatic extension; identity/nonfinite/reconstruction failures block affected acceptance.'})
   summary['paragraphs'].insert(1,{'next_phase_20260921':True,'zh':'研究问题：对于一个固定分类器及其固定概念，预定外部MEL病例中，各概念图片覆盖率在某征象指定非absent类别与absent类别间是否呈现可描述的分布差异？12项（5×2＋2）为预定描述性对比，提供图片级关联，不证明语义等同、空间定位或患者独立性；K概念有12K相关比较，不计算确认性p值。H/M代码和配置已固定本地提交227eedf5，18项软件检查通过；未推送、未部署、未提交，无医学实验，GPU门槛仍待将来的同一获批作业。',
    'en':'Research question: for one fixed classifier and its fixed concepts, do image-level concept coverage distributions differ descriptively between each prespecified non-absent sign category and its absent reference in the predefined external MEL cohort? Twelve contrasts (5x2+2) supply image-level association, not semantic identity, spatial localization or patient independence; K concepts give12K dependent comparisons with no confirmatory p values. H/M code/configs are pinned in local commit227eedf5;18software checks passed. Not pushed/deployed/submitted, no medical experiment; GPU gates remain inside a future single approved job.'})
   for name,label in [('workload-comparison.csv','训练工作量：算术对比，非实测 / Training workload: arithmetic, not timing'),('approval-package.csv','H/R/S/M最终待批准组合和资源 / Final pending approval package and resources')]:
    f=preparation/name
    summary['artifacts'].insert(0,dict(path=str(f),sha256=sha(f),kind='table',caption=label))
   for f,label in [(preparation/'code-receipt.json','已准备源码版本；未执行 / Prepared source identity; not executed'),(preparation/'software-checks-final.txt','18项本地软件检查，非医学实验 / 18 local software checks, not medical experiments'),(ROOT/'configs/medical/medical-classifier.proposed.json','M可审阅配置；未批准 / M reviewable unapproved config'),(ROOT/'configs/medical/medical-overlap.proposed.json','H可审阅配置；未批准 / H reviewable unapproved config')]:
    docs[str(f)]=dict(path=str(f),label=label,sha256=sha(f))
 approved=ROOT/'artifacts/bunya/medical-approved-20260922'
 if (approved/'handover.json').exists():
  execution=json.loads((approved/'handover.json').read_text())
  # Current explicit authorization supersedes pending planning summaries, not history files.
  summary['paragraphs']=[x for x in summary['paragraphs'] if not x.get('next_phase_20260921')]
  summary['paragraphs'].insert(0,{'next_phase_20260921':True,'zh':'2026-09-22已明确批准H＋R101＋S描述性＋M50/batch64/训练seed43及部署预算。H '+execution['H_job']+'、M '+execution['M_job']+'分别提交，仅依赖共同部署28781904，彼此无依赖。完整版本'+execution['commit']+'已推送并通过Slurm部署；部署6秒、退出0:0，实际release/launcher/config及独立就绪检查通过。H上限4CPU/8GiB/30min/0GPU/2GiB，M上限1L40S/4CPU/16GiB/4h/5GiB。状态仅已提交，未收集/未验收；按用户要求停止等待，通知完成后再收集，失败不重提/扩容。',
   'en':'Explicit approval on22September: H + R101 + descriptive S + M50/batch64/training-seed43 and deployment budget. H '+execution['H_job']+' and M '+execution['M_job']+' submitted independently, depending only on deployment28781904. Commit'+execution['commit']+' was pushed and Slurm-deployed; deployment completed0:0 in6s with release/launcher/config identities and independent readiness checks verified. H cap4CPU/8GiB/30min/0GPU/2GiB; M cap1L40S/4CPU/16GiB/4h/5GiB. Submitted only, not collected/accepted. Await user completion notification; no retry or expansion.'})
  summary['paragraphs'].insert(1,{'next_phase_20260921':True,'zh':'R101和S批准的是协议，不包含医学概念发现或外部推理。M完成后区分工程验收与研究适用性，报告七类/melanoma表现及训练曲线，再提出发现预算；不因低分重训，不将数值检查视为医学适用性。单seed只解释一个固定分类器；50轮是固定预算窗口。覆盖率与12项比较仅提供图片级关联，不证明语义等同或空间定位。原主计划仍定义总体目标及未被替代规则，历史提案保留；较新推荐不自动获批。此前图像、模型、概念及已验收结果不变。',
   'en':'R101 and S approve protocols only, excluding medical concept discovery and external inference. After M, distinguish engineering acceptance from research suitability, report class-level/melanoma performance and learning curves, then propose discovery resources. No low-score refit; numerical checks do not certify medical utility. One seed conditions on one fixed classifier;50epochs is a bounded window. Coverage and12contrasts address image-level association, not semantic identity or spatial localization. The main plan retains overall goals and unchanged rules; historical proposals remain, and newer recommendations are not approvals. Existing accepted results and inputs remain unchanged.'})
  summary['artifacts']=[a for a in summary['artifacts'] if 'medical-approved-20260922' not in a['path'] and not a['path'].endswith('/preparation/approval-package.csv')]
  f=approved/'submission-table.csv';summary['artifacts'].insert(0,dict(path=str(f),sha256=sha(f),kind='table',caption='本次明确批准与实际提交；不是结果验收 / Explicit approval and actual submissions; not result acceptance'))
  for f,label in [(approved/'authorization.json','本次原始批准及替代范围 / Explicit approval and superseded choices'),(approved/'handover.json','H/M实际提交交接 / H/M submission handover'),(approved/'release.json','实际部署版本及科学代码未改变证明 / Deployed release and unchanged scientific-code identity'),(approved/'deployment-readiness.json','Slurm内独立H/M提交前检查 / Independent H/M preflight inside Slurm'),(ROOT/'configs/medical/medical-classifier.approved.json','M已批准配置 / Approved M configuration'),(ROOT/'configs/medical/medical-overlap.approved.json','H已批准配置 / Approved H configuration')]:
   docs[str(f)]=dict(path=str(f),label=label,sha256=sha(f))
  for d in docs.values():
   if d['path'].endswith('.proposed.json'):d['label']='历史提案（批准副本另列） / Historical proposal (approved copy listed separately)'
 results=ROOT/'artifacts/bunya/medical-results-20260922'
 if (results/'acceptance.json').exists():
  accepted=json.loads((results/'acceptance.json').read_text())
  if accepted['status']!='PASS_ENGINEERING_WITH_RESEARCH_LIMITATIONS':raise ValueError('Medical acceptance scope changed')
  summary['paragraphs']=[x for x in summary['paragraphs'] if not x.get('next_phase_20260921')]
  summary['paragraphs'].insert(0,{'next_phase_20260921':True,'zh':'医学H/M最新验收：部署28781904、H28781914、M28781915均COMPLETED0:0，耗时6/88/782秒；完整收集与工程验收通过。执行版本00f06dc549439db92e4842cb5ecd761f9b38bc43。H全部10,125,165图片对完成，native/canonical224精确匹配均0；4,291阈值候选不是重复计数。R101有214阈值对涉及20病例，源train/val/test=180/12/22；全部候选原图与人工表见下方入口，尚未确认身份或排除。',
   'en':'Latest medical H/M acceptance: deployment28781904, H28781914 and M28781915 completed0:0 in6/88/782s; complete collections and engineering checks passed. Executed commit00f06dc549439db92e4842cb5ecd761f9b38bc43. H completed10,125,165image pairs, with zero native/canonical224exact matches.4,291threshold candidates are not duplicate counts. R101has214threshold pairs across20cases, source train/val/test180/12/22; all pair images and unreviewed forms are linked below. No identity confirmation or exclusion.'})
  summary['paragraphs'].insert(1,{'next_phase_20260921':True,'zh':'M50轮/6,450更新/410,750图次完整；验证选中epoch10后冻结再test。测试accuracy89.00%、balanced59.70%、macroAUC0.96867；MEL50/70（61病灶），precision50/89、AUC0.94410。DF验证0/5、测试0/8召回，且val/test从无DF最终预测；不等同于已证实代码错误。后期train loss下降而val loss上升，保留固定模型，不自动重训。工程通过不等于医学适用性。',
   'en':'M completed50epochs/6,450updates/410,750visits; validation selected epoch10, frozen before final test. Test accuracy89.00%, balanced59.70%, macroAUC0.96867; MEL50/70images (61lesions), precision50/89, AUC0.94410. DF recall0/5validation and0/8test, with no DF argmax anywhere in either set; this is not a confirmed code defect. Later training loss fell while validation loss rose. Retain the frozen model; no automatic refit. Engineering PASS does not certify medical utility.'})
  summary['paragraphs'].insert(2,{'next_phase_20260921':True,'zh':'本轮无新实验、预测或作业。R101/S仅协议批准；医学HU发现和外部推理仍未授权。下一批源域400病灶/70held-out及部署的具体配置与上限在结果说明中，仅为待批提案。现有十类概念、评价、9例基础人工审阅、数据身份与失败历史全部保留。GPU利用率/显存峰值及train accuracy未记录，明确缺失而不虚构。',
   'en':'No new experiments, predictions or jobs this turn. R101/S are protocol-only approvals; medical HU discovery and external inference remain unauthorized. The result note proposes a source400lesion/70held-out run and deployment caps, not approved execution. Existing ten-class concepts/evaluations, nine-case basic review, data identities and failure history remain. GPU utilization/peak VRAM and training accuracy were not recorded and are explicitly unavailable.'})
  summary['artifacts']=[a for a in summary['artifacts'] if 'medical-results-20260922' not in a['path'] and not a['path'].endswith('medical-approved-20260922/submission-table.csv')]
  for f,kind,label in [(results/'job-results.csv','table','H/M最终状态、资源和验收范围 / H/M final state, resources and acceptance'),(results/'bundle/M-class-metrics.csv','table','M七类指标及图片/病灶分母 / M seven-class metrics and image/lesion denominators'),(results/'bundle/figures/M-training-curves.png','curve','M训练损失与验证曲线；不是训练accuracy / M training loss and validation curves; not training accuracy'),(results/'bundle/figures/M-confusion-matrices.png','curve','M验证/测试混淆矩阵：计数及行比例 / M validation/test confusion matrices: counts and row proportions')]:
   summary['artifacts'].insert(0,dict(path=str(f),sha256=sha(f),kind=kind,caption=label))
  manifest=results/'bundle/bundle-manifest.json'
  summary['review_bundles']=[b for b in summary.get('review_bundles',[]) if b['id']!='medical-hm-results-20260922']
  summary['review_bundles'].insert(0,dict(id='medical-hm-results-20260922',manifest=str(manifest),sha256=sha(manifest),label='医学结果、全部5913成对图片与R101优先审阅 / Medical results, all5913pairs and R101 priority review'))
  for f,label in [(ROOT/'docs/MEDICAL_RESULTS_20260922.zh-en.md','H/M结果、限制与下一批未批准预算 / H/M results, limitations and unapproved next-batch budget'),(results/'acceptance.json','H/M工程验收凭据；非医学认证 / H/M engineering receipt; not medical certification'),(results/'obsidian-update.json','英文Implementation Notes更新范围 / English implementation-note update scope')]:
   docs[str(f)]=dict(path=str(f),label=label,sha256=sha(f))
  for name,label in [('browser-qa.json','离线页面与审阅导出检查 / Offline pages and review-export checks'),('static-link-qa.json','全部成对页面链接检查 / All pair-page link checks'),('configuration-followthrough.json','学习率、精度和checkpoint组件复核 / Learning rate, precision and checkpoint component checks'),('protected-check.json','受保护文件及原计划保留检查 / Protected files and plan preservation')]:
   f=results/name
   if f.exists():docs[str(f)]=dict(path=str(f),label=label,sha256=sha(f))
 discovery=ROOT/'artifacts/bunya/medical-discovery-20260922'
 if (discovery/'handover.json').exists():
  latest=json.loads((discovery/'handover.json').read_text())
  for paragraph in summary['paragraphs']:
   if paragraph.get('next_phase_20260921'):
    paragraph['zh']=paragraph.get('zh','').replace('本轮无新实验、预测或作业。R101/S仅协议批准；医学HU发现和外部推理仍未授权。下一批源域400病灶/70held-out及部署的具体配置与上限在结果说明中，仅为待批提案。','此前H/M验收没有新增实验。当前医学源域D0+D1+部署已获明确批准，实际提交状态见本区最上方；R101/S仍仅协议批准，外部推理未授权。')
    paragraph['en']=paragraph.get('en','').replace('No new experiments, predictions or jobs this turn. R101/S are protocol-only approvals; medical HU discovery and external inference remain unauthorized. The result note proposes a source400lesion/70held-out run and deployment caps, not approved execution.','The prior H/M acceptance added no experiments. Source medical D0+D1+deployment are now explicitly approved; see current submission status above. R101/S remain protocol-only and external inference is unauthorized.')
  summary['paragraphs'].insert(0,{'next_phase_20260921':True,'zh':'首次医学HU发现已批准（固定epoch10/400病灶各1图/全部70held-out）。版本'+latest['commit']+'已推送。部署28790767已完成0:0/6秒；D0 '+latest['D0_job']+'已提交，唯一提交后核对时运行中，未验收。D1因助手误填qos=normal被gpu_cuda拒绝，无作业编号；仅改short的具体方案已准备，因“失败不自动重提”等待单次重提许可（MED26-016）。D1上限1L40S/8CPU/32GiB/2h/15GiB不变，外部推理/重训仍不执行。',
   'en':'First medical HU discovery approved: fixed epoch10,400distinct lesions/one image each, all70held-out. Commit'+latest['commit']+' pushed. Deployment28790767 completed0:0 in6s; D0 '+latest['D0_job']+' submitted and running at the single post-submission check, not accepted. D1was rejected before job creation because the assistant usedqosnormal on gpu_cuda. A short-only correction is prepared; one-time retry permission is pending under the no-auto-retry rule (MED26-016). D1cap remains1L40S/8CPU/32GiB/2h/15GiB; no external inference or classifier refit.'})
  summary['paragraphs'].insert(1,{'next_phase_20260921':True,'zh':'MED26-015说明修正：outlier_percentile=1.0是100%分位点，有限行无此项离群剔除，并非剔除1%；参数保持1.0。初始cluster数沿用int(mean+std)片段数启发式，不是搜索。SAM1%面积、零特征排除及mincluster50分别记录；全部原始masks/features仍保存。医学适配通过后才在同一D1作业内执行整批，无额外SAM probe。',
   'en':'MED26-015 clarification: outlier_percentile1.0 is the100thpercentile and removes no finite rows under the strict comparison, not1percent removal. Keepq1. Initial cluster count retains the int(mean+std) segment-count heuristic, not a search. SAM1percent area, exact-zero exclusion and mincluster50 are separate rules; retain all raw masks/features. Same-job medical adapter checks gate the full D1run; no additional SAM probe.'})
  if latest.get('current_summary_zh'):
   summary['paragraphs'][0].update(zh=latest['current_summary_zh'],en=latest['current_summary_en'])
  for f,label in [(ROOT/'docs/MEDICAL_DISCOVERY_EXECUTION_20260922.zh-en.md','已批准医学D0/D1完整协议 / Approved medical D0/D1 protocol'),(discovery/'handover.json','首次医学发现实际提交状态 / Actual first-discovery submission status'),(discovery/'D1-qos-correction.json','D1历史QoS修正计划 / Historical D1 QoS correction plan'),(discovery/'obsidian-sync.json','医学发现Implementation Notes同步 / Discovery implementation-note synchronization')]:
   docs[str(f)]=dict(path=str(f),label=label,sha256=sha(f))
  for name,label in [('D1-dependency-diagnostic.json','已完成依赖退出活动记录的证据 / Evidence of completed dependencies leaving active records'),('D1-scheduler-test-only.json','调度验证，不是实际提交 / Scheduler validation, not submission'),('D1-expired-dependency-correction.json','失效依赖修正方案的历史准备凭据 / Historical preparation of expired-dependency correction'),('D1-dependency-retry-authorization.json','用户单次修正提交授权 / Explicit one-time corrected-submission authorization'),('D1-final-submission.json','D1实际成功提交回执 / Actual successful D1 submission receipt')]:
   f=discovery/name
   if f.exists():docs[str(f)]=dict(path=str(f),label=label,sha256=sha(f))
 batch=ROOT/'artifacts/bunya/batch-review-20260922'
 if (batch/'current-summary.json').exists():
  current_batch=json.loads((batch/'current-summary.json').read_text())
  # Replace stale current-state prose, retaining linked historical receipts/docs.
  summary['paragraphs']=[x for x in summary['paragraphs'] if not x.get('next_phase_20260921')]
  summary['paragraphs'].insert(0,dict(next_phase_20260921=True,zh=current_batch['current_summary_zh'],en=current_batch['current_summary_en']))
  summary['paragraphs'].insert(1,dict(next_phase_20260921=True,zh='医学C001可查看训练/留出并排的原型、固定随机、低间隔诊断以及三个初始cluster。只有一个学习子空间，不能直接命名为医学征象；completeness0.662911不是可理解性。固定随机留出中存在中心被遮蔽的例子，视觉一致性待人工审阅。既有H/M、9例基础审阅、失败历史和原十类/基线结果完整保留。',en='MedicalC001 has side-by-side training/held-out prototypes, fixed random and low-margin examples, plus all three initial clusters. One learned subspace is not a medical sign; completeness0.662911 is not understandability. Some fixed random held-out examples hide central regions; semantic consistency remains for manual review. PriorH/M, nine-case basic review, failures and original ten-class/baseline results remain preserved.'))
  summary['paragraphs'].insert(2,dict(next_phase_20260921=True,zh='关键限制：A四类缩批对照失败，后续条件缺失，未放宽容差/重提。医学模型DF零召回、单seed及病例非患者身份限制仍有效。原分类器batch64与发现batch8的70张全图预测一致，logit最大差0.0184；同batch医学适配差0。E224在SAM前缩放224×224、保留101例和所有原标签，不排除H的20例相似候选、不声称独立患者或空间定位。新外部结果尚未收集；不会生成占位结果。',en='Key limits: four A reduced-batch controls failed; later conditions are missing, with no tolerance change/retry. MedicalDF zero recall, single seed and unknown patient identity remain limits. All70full-image predictions agree between classifierbatch64 and discoverybatch8, with maximum logit difference0.0184; same-batch medical adapter difference0. E224warps to224×224beforeSAM, retaining all101cases/rawlabels and20unconfirmed H candidate cases; no patient-independence/localization claim. New external results are not collected; no placeholder outcomes.'))
  manifest=batch/'bundle/manifest.json'
  if manifest.exists():
   summary['review_bundles']=[b for b in summary.get('review_bundles',[]) if b['id']!='batch-review-20260922']
   summary['review_bundles'].insert(0,dict(id='batch-review-20260922',manifest=str(manifest),sha256=sha(manifest),label='本批验收、医学概念及mask变化视觉报告 / Batch acceptance, medical concepts and mask-change gallery'))
  extras=[(ROOT/'docs/BATCH_RESULTS_20260922.zh-en.md','本批实际结果、缺失与科研限制 / Current batch outcomes, missing conditions and research limits'),(ROOT/'docs/MEDICAL_EXTERNAL_EXECUTION_20260922.zh-en.md','已批准并提交E224/R101/S协议 / Approved and submitted E224/R101/S protocol'),(batch/'acceptance-both.json','完整本地验收，非新推理 / Complete local acceptance; no new inference'),(batch/'all-worker-anomalies.json','本批全部worker异常原始记录 / All raw worker anomaly records'),(batch/'classifier-binding-and-heldout-replay.json','固定分类器身份与70图跨batch缓存比较 / Frozen classifier identity and70-image cached batch comparison'),(batch/'shared-science-version-comparison.json','A/D1科学源码一致性 / Identical shared science across A/D1'),(ROOT/'artifacts/bunya/medical-external-20260922/handover.json','E224实际提交及资源 / Actual E224 submissions and resources')]
  for f,label in extras:
   if f.exists():docs[str(f)]=dict(path=str(f),label=label,sha256=sha(f))
  for doc in docs.values():
   if '待选' in doc['label'] or '未批准' in doc['label'] or 'pending protocol' in doc['label']:doc['label']='历史提案，当前批准见E224协议 / Historical proposal; current approval in E224 protocol: '+doc['label']
  for artifact in summary.get('artifacts',[]):
   if artifact.get('path','').endswith('candidate-scopes.csv'):artifact['caption']='历史候选范围计数；现已冻结R101 / Historical cohort counts; R101 now frozen'
   if artifact.get('path','').endswith('proposed-contrasts.csv'):artifact['caption']='征象对比元数据分母；S描述性已批准，外部结果待收集 / Sign-label denominators; descriptive S approved, external results not collected'
  summary['artifacts']=[x for x in summary.get('artifacts',[]) if 'batch-review-20260922' not in x.get('path','')]
  for name,label in [('robustness-conditions.csv','A条件、分母及区间 / A conditions, denominators and intervals'),('medical-split-summary.csv','医学训练与留出结果 / Medical training and held-out outcomes'),('medical-concept-index.csv','医学稳定概念索引 / Stable medical concept index')]:
   f=batch/name;summary['artifacts'].append(dict(path=str(f),sha256=sha(f),kind='table',caption=label))
 data['documents']=list(docs.values());data['updated_at']=status['updated_at'];data['preparation_workstreams']=status
 data['anomalies']=[json.loads(line.replace('clinic→derm replacement','replacement of clinic images with derm images')) for line in (ROOT/'docs/ANOMALIES.jsonl').read_text().splitlines() if line.strip()]
 p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
 print('Updated existing report data and scoped medical evidence; existing accepted collections unchanged')
if __name__=='__main__':main()
